/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NewComponent {
    'age': number;
    /**
    * The first name
    */
    'name': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNewComponentElement extends Components.NewComponent, HTMLStencilElement {}
  const HTMLNewComponentElement: {
    prototype: HTMLNewComponentElement;
    new (): HTMLNewComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'new-component': HTMLNewComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NewComponent {
    'age'?: number;
    /**
    * The first name
    */
    'name'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'new-component': NewComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'new-component': LocalJSX.NewComponent & JSXBase.HTMLAttributes<HTMLNewComponentElement>;
    }
  }
}


